name: remindme
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Existing dependencies
  flutter_sound: ^9.2.13        # For voice recording
  permission_handler: ^11.1.0   # For microphone & camera permission
  image_picker: ^1.1.2          # For camera & gallery

<<<<<<< HEAD
  # Added based on your request
  record: ^5.0.4                # Audio recording plugin
  path_provider: ^2.1.4         # For storing audio files
=======
  # Added for playing ringtone sounds
  audioplayers: ^5.2.1
>>>>>>> e824206 (Edites ringtone opiton with sounds andadded text fields)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/
