name: remindme
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ---- Firebase (Compatible Versions) ----
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.2.10

  # Local notifications
  flutter_local_notifications: ^17.2.0

  # Other packages
  otp: ^3.1.3
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  share_plus: ^10.0.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  intl: ^0.19.0
  url_launcher: ^6.3.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/1.png
    - assets/
