name: remind_me
description: Medicine Reminder App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Core Icons ---
  cupertino_icons: ^1.0.8

  # --- Networking & Storage ---
  http: ^1.2.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2        # Required for saving report temporary file

  # --- Firebase & Notifications ---
  firebase_core: ^3.6.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1     # Fix for Android setup

  # --- Media (Images & Audio) ---
  image_picker: ^1.1.2
  audioplayers: ^6.0.0
  flutter_sound: ^9.2.13
  gal: ^2.3.0 # Required to save report to Gallery

  # --- Utilities ---
  intl: ^0.19.0
  permission_handler: ^11.3.1  # Required for gallery permissions
  url_launcher: ^6.3.0
  qr_flutter: ^4.1.0

  # --- Sharing & Screenshots ---
  screenshot: ^3.0.0           # Required to capture the report
  share_plus: ^10.0.0          # Required to share the report image

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/
    # If you have specific files, you can list them,
    # but 'assets/' covers everything in that folder.
    # - assets/1.png
    # - assets/email.png